# Generated by Django 5.2.11 on 2026-02-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(default='', max_length=10)),
                ('load_mode', models.CharField(choices=[('CUSTOMER_AGG', 'Agregado por cliente'), ('OPERATION', 'Por operación')], max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_loaded', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('errors_json', models.TextField(blank=True, default='')),
                ('source_columns_json', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=32, unique=True)),
                ('oficina', models.CharField(blank=True, default='', max_length=32)),
                ('tipo_credito', models.CharField(blank=True, default='', max_length=64)),
                ('garantia', models.CharField(blank=True, default='', max_length=64)),
                ('sexo', models.CharField(blank=True, default='', max_length=8)),
                ('calificacion_riesgo', models.CharField(blank=True, default='', max_length=8)),
                ('n_operaciones', models.IntegerField(blank=True, null=True)),
                ('n_vigentes', models.IntegerField(blank=True, null=True)),
                ('monto_total', models.FloatField(blank=True, null=True)),
                ('saldo_total', models.FloatField(blank=True, null=True)),
                ('plazo_prom', models.FloatField(blank=True, null=True)),
                ('tasa_prom', models.FloatField(blank=True, null=True)),
                ('patrimonio_tec', models.FloatField(blank=True, null=True)),
                ('max_dias_mora', models.IntegerField(blank=True, null=True)),
                ('antiguedad_max_dias', models.IntegerField(blank=True, null=True)),
                ('dias_hasta_ultimo_venc', models.IntegerField(blank=True, null=True)),
                ('riesgo_actual', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datahub.databatch')),
            ],
        ),
        migrations.CreateModel(
            name='CreditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=32)),
                ('oficina', models.CharField(blank=True, default='', max_length=32)),
                ('estado', models.CharField(blank=True, default='', max_length=32)),
                ('fecha_concesion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_corte_base', models.DateField(blank=True, null=True)),
                ('monto_otorgado', models.FloatField(blank=True, null=True)),
                ('saldo_total', models.FloatField(blank=True, null=True)),
                ('tipo_credito', models.CharField(blank=True, default='', max_length=64)),
                ('plazo', models.IntegerField(blank=True, null=True)),
                ('tasa_interes', models.FloatField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, default='', max_length=64)),
                ('calificacion_riesgo', models.CharField(blank=True, default='', max_length=8)),
                ('dias_mora', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, default='', max_length=8)),
                ('patrimonio_tec', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datahub.databatch')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente'], name='datahub_cre_cliente_65756a_idx')],
            },
        ),
    ]
