# Generated by Django 5.2.11 on 2026-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraggregate',
            name='calificacion_riesgo',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D', 'D'), ('E', 'E')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='customeraggregate',
            name='garantia',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personal'), ('HIPOTECARIA', 'Hipotecaria'), ('PRENDARIA', 'Prendaria'), ('SOLIDARIA', 'Solidaria')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customeraggregate',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro/No declara')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='customeraggregate',
            name='tipo_credito',
            field=models.CharField(blank=True, choices=[('CONSUMO', 'Consumo'), ('MICROCREDITO', 'Microcrédito'), ('COMERCIAL', 'Comercial'), ('VIVIENDA', 'Vivienda')], default='', max_length=64),
        ),
    ]
