# Generated by Django 5.2.11 on 2026-02-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_alter_customeraggregate_calificacion_riesgo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraggregate',
            name='ml_pred_last',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraggregate',
            name='ml_proba_last',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraggregate',
            name='ml_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraggregate',
            name='ml_scored_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
