# Generated by Django 5.2.11 on 2026-02-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraggregate',
            name='categoria_norma',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customeraggregate',
            name='nivel_norma',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='CustomerRiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_anterior', models.CharField(blank=True, max_length=2, null=True)),
                ('categoria_nueva', models.CharField(max_length=2)),
                ('nivel', models.CharField(max_length=32)),
                ('dias_mora', models.IntegerField(default=0)),
                ('tipo_credito', models.CharField(blank=True, max_length=32, null=True)),
                ('proba_ml', models.FloatField(blank=True, null=True)),
                ('proba_final', models.FloatField(blank=True, null=True)),
                ('pred_ml', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to='datahub.customeraggregate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
